7 1 message brokers
thinknetica-django-lab-03/DoomLordor pull request #73
Opened 2021-06-23 14:05 UTC by DoomLordor

Closes #46

2021-06-23 16:42 UTC, morgangt requested changes

2021-06-23 16:42 UTC, morgangt commented on Lab_Thinknetica/settings.py
> +        "LOCATION": "redis://192.168.0.3:6379/1",
вынести этот ip адрес в конфигурируем параметры, предлогам начать использовать .env файлы 
подробнее о них тут: https://www.digitalocean.com/community/tutorials/how-to-harden-your-production-django-project
В вашем случае надо использовать сервер redis://redis:6379/1
и ваше приложение тоже запускать в докере

2021-06-24 15:21 UTC, DoomLordor commented on Lab_Thinknetica/settings.py
> +        "LOCATION": "redis://192.168.0.3:6379/1",
Я вынес некоторые настройки в .env файл

2021-06-25 09:16 UTC, morgangt approved these changes

2021-06-25 10:02 UTC, merged